---
title: "CCES Analysis for Capstone"
author: "Ellie Mitchell"
date: "2023-11-01"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Data Cleaning
```{r}
library(tidyverse)
library(ggplot2)
library(stargazer)
library(interflex)
library(corto)
library(broom)

file_path <- "/Users/rental/Desktop/Writing Sample Code/"
table_path <- "/Users/rental/Desktop/Writing Sample Code/Table/"
plot_path <- "/Users/rental/Desktop/Writing Sample Code/Plots/"

cces <- read.csv(str_c(file_path,
                       "cces.csv"))

# Creating a binary variable for each of my religious groups; my plan is to put each of these variables together in one regression

# Binary variable for Mormons
cces$mormon <- ifelse(cces$religpew == 3, 1, 0)
table(cces$mormon)

# Binary variable for Muslims
cces$muslim <- ifelse(cces$religpew == 6, 1, 0)
table(cces$muslim)

# Binary variable for Jews
cces$jew <- ifelse(cces$religpew == 5, 1, 0)
table(cces$jew)

# Binary variable for Catholics
cces$catholic <- ifelse(cces$religpew == 2, 1, 0)
table(cces$catholic)

# Now that I've created my independent variables, I'm going to create new variables for my dependent variables. I'm going to make these on a scale between 0 and 1.
# Health care DV
table(cces$CC22_327a)
cces$CC22_327a[cces$CC22_327a == 2] <- 0
table(cces$CC22_327a)
# Now the variable is on a scale from 0-1, where support = 1 and oppose = 0.

# Immigration DV
table(cces$CC22_331c)
cces$CC22_331c[cces$CC22_331c == 2] <- 0
table(cces$CC22_331c)
# This variable is also on a scale from 0-1 now, where support = 1 and oppose = 0

# Abortion DV
table(cces$CC22_332a)
cces$CC22_332a[cces$CC22_332a == 2] <- 0
table(cces$CC22_332a)
# Same scale of 0-1 now, support = 1 and oppose = 0

# Trust in the federal government DV
table(cces$CC22_423)
cces$CC22_423[cces$CC22_423 == 1] <- 1
cces$CC22_423[cces$CC22_423 == 2] <- 0.6666
cces$CC22_423[cces$CC22_423 == 3] <- 0.33333
cces$CC22_423[cces$CC22_423 == 8] <- 0
table(cces$CC22_423)
# Scale of 0-1, 0 = None at all and 1 = A great deal

# Making my control variables:
# Creating a pid7 variable
table(cces$pid7)

# Getting rid of the don't knows, because theoretically they don't matter:
cces <- cces[cces$pid7 != 8, ]
cces <- cces[cces$pid7 != 4, ]

cces$democrat <- ifelse(cces$pid7 %in% c(1,2,3), 1, 0)
table(cces$democrat)

cces$pid2 <- ifelse(cces$pid7 %in% c(1,2), 1, 0)

cces$pid1 <-ifelse(cces$pid7 %in% c(1), 1, 0)

# State someone is from
# NOTE: if this doesn't matter when I do the regression, I'll use a region variable instead
table(cces$inputstate)
# Don't need to do anything to this variable since I'm not going to drop anything
table(cces$region)
# Same here, this all looks good

# Gender
table(cces$gender4)
cces$gender4[cces$gender4 == 1] <- 1
cces$gender4[cces$gender4 == 2] <- 2
cces$gender4[cces$gender4 == 3] <- 3
cces$gender4[cces$gender4 == 4] <- 3
# For ease analysis, made it so there were just three gender options (male, female, other) instead of four since both 'other' options have really small n sizes anyways

# Family Income
table(cces$faminc_new)
# Dropping the people who didn't answer
cces <- cces[cces$faminc_new != 97, ]
table(cces$faminc_new)

# Education
table(cces$educ)
# Don't need to drop anything from this

# Race
table(cces$race)
# Don't need to drop anything here either

# Employ
table(cces$employ)
# No need to drop anything here either

# Creating a religiosity control variable:
# First, checking each variable before I create the new variable.
table(cces$pew_religimp)
# 1 is very important, 2 is somewhat important, 3 is not too important, and 4 is not at all important

table(cces$pew_churatd)
# Dropping the don't knows
cces <- cces[cces$pew_churatd != 7, ]
table(cces$pew_churatd)
# 1 is more than once a week, 2 is once a week, 3 is once or twice a month, 4 is a few times a year, 5 is seldom, 6 is never, 7 is don't know

table(cces$pew_prayer)
# Dropping the don't knows
cces <- cces[cces$pew_prayer != 8, ]
table(cces$pew_prayer)
# 1 is several times a day, 2 is once a day, 3 is a few times a week, 4 is once a week, 5 is a few times a month, 6 is seldom, 7 is never, 8 is don't know

# Creating the new religiosity variable
# To create, I use the questions pew_religimp and pew_prayer. I add the values together and then divide. I decided to not use the other variable b/c of the studies that indicate that sometimes church attendance is based simply on social aspects. I didn't want that to influence my measurement of religiosity
cces <- cces |>
  mutate(religiosity = ((pew_religimp + pew_prayer)/2))

table(cces$religiosity)

cces$religiosity[cces$religiosity == 1] <- 1
cces$religiosity[cces$religiosity == 1.5] <- 0.8888888
cces$religiosity[cces$religiosity == 2] <- 0.7777777
cces$religiosity[cces$religiosity == 2.5] <- 0.6666666
cces$religiosity[cces$religiosity == 3] <-  0.5555555
cces$religiosity[cces$religiosity == 3.5] <- 0.4444444
cces$religiosity[cces$religiosity == 4] <- 0.3333333
cces$religiosity[cces$religiosity == 4.5] <- 0.2222222
cces$religiosity[cces$religiosity == 5] <- 0.1111111
cces$religiosity[cces$religiosity == 5.5] <- 0
table(cces$religiosity)
# I now have a variable where religiosity is between 0-1, 0 being the most religious and 1 being the least

# Also adding in a control for Christian nationalism. There was no question asked directly about this, so I decided to use vote for Trump as my indicator instead.
table(cces$presvote20post)
cces$trump <- ifelse(cces$presvote20post == 2, 1, 0)
table(cces$trump)
# 1 = vote for Trump, 0 = did not vote for Trump
```

Regressions 
```{r}
library(stargazer)

# Health Care Reg
healthcare <- lm(CC22_327a ~ mormon + muslim + jew + catholic + democrat + as.factor(region) + as.factor(gender4) + faminc_new + educ + as.factor(race) + employ + religiosity + trump, 
                 data = cces)

summary(healthcare)

# Immigration Reg
immigration <- lm(CC22_331c ~ mormon + muslim + jew + catholic + democrat + as.factor(region) + as.factor(gender4) + faminc_new + educ + as.factor(race) + employ + religiosity + trump, 
                  data = cces)

summary(immigration)

# Abortion Reg
abortion <- lm(CC22_332a ~ mormon + muslim + jew + catholic + democrat + as.factor(region) + as.factor(gender4) + faminc_new + educ + as.factor(race) + employ + religiosity + trump, 
               data = cces)

summary(abortion)

# Trust in the Federal Government Reg
trust <- lm(CC22_423 ~ mormon + muslim + jew + catholic + democrat + as.factor(region) + as.factor(gender4) + faminc_new + educ + as.factor(race) + employ + religiosity + trump,
            data = cces)

summary(trust)

# Combining them into one table
stargazer(healthcare, 
          immigration, 
          abortion, 
          trust, 
          covariate.labels = c("Intercept", 
                               "Mormons", 
                               "Muslims", 
                               "Jews", 
                               "Catholics", 
                               "Democrats", 
                               "Midwest", 
                               "South", 
                               "West", 
                               "Woman", 
                               "Other Gender", 
                               "Income", 
                               "Education", 
                               "Black", 
                               "Hispanic", 
                               "Asian",
                               "Native American",
                               "Middle Eastern", 
                               "Two or More Races", 
                               "Other Race", 
                               "Employment", 
                               "Religiosity", 
                               "Christian Nationalism"), 
          type = "html",
          style = "apsr", 
          title = "Basic Regression Results",
          dep.var.labels=c("Healthcare",
                           "Immigration",
                           "Abortion",
                           "Trust in the Federal Government"), 
          notes = c("Base categories: Northeast, Male, White"),
          intercept.bottom = FALSE, 
          intercept.top=TRUE, 
          out = str_c(table_path,
                      "basicreg.htm"))
```

Regressions, using a more concentrated definition of PID
```{r}
# Healthcare Reg
healthcare <- lm(CC22_327a ~ mormon + muslim + jew + catholic + pid2 + as.factor(region) + as.factor(gender4) + faminc_new + educ + as.factor(race) + employ + religiosity + trump, 
                 data = cces)

summary(healthcare)

# Immigration Reg
immigration <- lm(CC22_331c ~ mormon + muslim + jew + catholic + pid2 + as.factor(region) + as.factor(gender4) + faminc_new + educ + as.factor(race) + employ + religiosity + trump, 
                  data = cces)

summary(immigration)

# Abortion Reg
abortion <- lm(CC22_332a ~ mormon + muslim + jew + catholic + pid2 + as.factor(region) + as.factor(gender4) + faminc_new + educ + as.factor(race) + employ + religiosity + trump, 
               data = cces)

summary(abortion)

# Trust in the Federal Government Reg
trust <- lm(CC22_423 ~ mormon + muslim + jew + catholic + pid2 + as.factor(region) + as.factor(gender4) + faminc_new + educ + as.factor(race) + employ + religiosity + trump,
            data = cces)

summary(trust)

stargazer(healthcare, 
          immigration, 
          abortion, 
          trust, 
          covariate.labels = c("Intercept", 
                               "Mormons", 
                               "Muslims", 
                               "Jews", 
                               "Catholics", 
                               "Democrats", 
                               "Midwest",
                               "South",
                               "West", 
                               "Woman", 
                               "Other Gender", 
                               "Income", 
                               "Education", 
                               "Black",
                               "Hispanic", 
                               "Asian", 
                               "Native American", 
                               "Middle Eastern", 
                               "Two or More Races", 
                               "Other Race", 
                               "Employment", 
                               "Religiosity", 
                               "Christian Nationalism"), 
          type = "html", 
          style = "apsr", 
          title = "Regression Results with Limited PID",
          dep.var.labels=c("Healthcare",
                           "Immigration",
                           "Abortion",
                           "Trust in the Federal Government"), 
          notes = c("Base categories: Northeast, Male, White"),
          intercept.bottom = FALSE, 
          intercept.top=TRUE, 
          out = str_c(table_path,
                      "basicreg_smallerPID.htm"))
```

Regressions containing interactions
```{r}
# Here, I am going to interact religiosity with each religion (to see the true ethnic effect)

# Healthcare Base Regression
healthcareinteract <- lm(CC22_327a ~ mormon + muslim + jew + catholic + mormon*religiosity + muslim*religiosity + jew*religiosity + catholic*religiosity + democrat + as.factor(region) + as.factor(gender4) + faminc_new + educ + as.factor(race) + employ + religiosity + trump, data = cces)

summary(healthcareinteract)

# Looking specifically at the interactions, have to look at them for each religion individually (but I'll combine later)

# Looking at interactions/marginal effects for Mormons
relig.inter <- interflex("binning",
                         data = cces,
                         Y="CC22_423",
                         D="mormon",
                         X="religiosity",
                         Z = c("democrat", 
                               "region", 
                               "gender4", 
                               "faminc_new", 
                               "educ",
                               "race", 
                               "employ", 
                               "trump"),
                         na.rm=T)

marginaleffects1.df <- as.data.frame(relig.inter$est.bin)
marginaleffects1.df$z <- (relig.inter$est.bin$`1`[,2])/(relig.inter$est.bin$`1`[,3])
marginaleffects1.df$p <- z2p(marginaleffects1.df$z)

# For Muslims
relig.inter <- interflex("binning", 
                         data = cces,
                         Y="CC22_423",
                         D="muslim",
                         X="religiosity",
                         Z = c("democrat", 
                               "region",
                               "gender4",
                               "faminc_new",
                               "educ", 
                               "race", 
                               "employ", 
                               "trump"),
                         na.rm = T)
marginaleffects2.df <- as.data.frame(relig.inter$est.bin)
marginaleffects2.df$z <- (relig.inter$est.bin$`1`[,2])/(relig.inter$est.bin$`1`[,3])
marginaleffects2.df$p <- z2p(marginaleffects2.df$z)

# For Jews
relig.inter <- interflex("binning", 
                         data = cces,
                         Y="CC22_423",
                         D="jew",
                         X="religiosity",
                         Z = c("democrat", 
                               "region",
                               "gender4", 
                               "faminc_new", 
                               "educ", 
                               "race", 
                               "employ", 
                               "trump"),
                         na.rm=T)
marginaleffects3.df <- as.data.frame(relig.inter$est.bin)
marginaleffects3.df$z <- (relig.inter$est.bin$`1`[,2])/(relig.inter$est.bin$`1`[,3])
marginaleffects3.df$p <- z2p(marginaleffects3.df$z)

# For Catholics
relig.inter <- interflex("binning", 
                         data= cces,
                         Y="CC22_423",
                         D="catholic",
                         X="religiosity",
                         Z = c("democrat", 
                               "region",
                               "gender4", 
                               "faminc_new",
                               "educ",
                               "race", 
                               "employ",
                               "trump"),
                         na.rm=T)
marginaleffects4.df <- as.data.frame(relig.inter$est.bin)
marginaleffects4.df$z <- (relig.inter$est.bin$`1`[,2])/(relig.inter$est.bin$`1`[,3])
marginaleffects4.df$p <- z2p(marginaleffects4.df$z)

# Binding my four marginal effects data frames together:
alltogether.df  <- as.data.frame(rbind(
  marginaleffects1.df ,
  marginaleffects2.df,
  marginaleffects3.df,
  marginaleffects4.df
))

# Adding names to my new dataframes
colnames(alltogether.df) <- c("X",
                              "coef",
                              "sd",
                              "CI.lower",
                              "CI.upper",
                              "z",
                              "p")

# Adding names for each of the religion "treatments"
alltogether.df$Treatment <- as.factor(c("Mormon", "Mormon", "Mormon",
                                        "Muslim", "Muslim", "Muslim",
                                        "Jew", "Jew", "Jew",
                                        "Catholic", "Catholic", "Catholic"))

# And adding names for each of the religiosity attitudes
alltogether.df$Attitudes <- as.factor(rep(c("Least Religious", 
                                            "Average", 
                                            "Highly Religious"),
                                          4))

# For this analysis, I don't really care about the people who are of average religiosity, so I remove them here.
alltogether.df <- subset(alltogether.df, 
                         Attitudes != "Average")

# Adding stars I can use for p-values later
alltogether.df <- alltogether.df %>%
  mutate(star = case_when(p <=.1 & p > .05 ~ "+",
                          p <= .05 & p >.01 ~ "*",
                          p <= .01 & p >.001 ~ "**", 
                          p <= .001 ~ "***"))

# Now, I make a coefficient plot
dv1  <- ggplot(data = alltogether.df, 
               aes(Attitudes, 
                   coef, 
                   color = Treatment, 
                   shape = Treatment)) + 
  geom_point(stat="identity", 
             position = position_dodge(width = .3, 
                                       preserve = "total")) + 
  geom_linerange(data = alltogether.df,
                 aes(ymin=CI.lower,
                     ymax=CI.upper), 
                 position = position_dodge(width = .3, 
                                           preserve = "total")) + 
  coord_flip() + 
  theme(axis.title=element_text(size=8)) + 
  theme(axis.text=element_text(size=8)) + 
  theme(legend.text=element_text(size=7)) + 
  theme(legend.title=element_text(size=7)) +
  geom_hline(yintercept = 0, lty=2) +
  theme_bw() +
  theme(legend.position = "bottom", 
        panel.grid.minor.x = element_blank()) +
  scale_color_manual(values = c("#a11111", 
                                "darkblue", 
                                "#c9a808", 
                                "#019001")) +
  labs(y="ITT: Marginal Effects on Health Care", 
       x = "", 
       title = "",
       caption = "Bars indicate 95% confidence interval. Stars indicate statistical significance.") +
  geom_text(data = alltogether.df, 
            aes(label = star),
            position = position_dodge(width = .3),
            vjust = -.001, 
            show.legend = FALSE) + 
  theme(text = element_text(family = "serif"), 
        plot.caption = element_text(hjust = 0))

dv1

# Saving out the plot
ggsave(str_c(plot_path, "Marginal Effects Health Care Interaction.png"),
       plot = dv1,
       width = 6,
       height = 4,
       dpi = 300,
       bg = "white")

# I now replicate this process for immigration.
# Immigration Regression
immigrationinteract <- lm(CC22_331c ~ mormon + muslim + jew + catholic + mormon*religiosity + muslim*religiosity + jew*religiosity + catholic*religiosity + democrat + as.factor(region) + as.factor(gender4) + faminc_new + educ + as.factor(race) + employ + religiosity + trump, 
                          data = cces)

summary(immigrationinteract)

# Marginal Errors for Mormons
relig.inter <- interflex("binning", 
                         data = cces,
                         Y="CC22_331c",
                         D="mormon",
                         X="religiosity",
                         Z = c("democrat", 
                               "region", 
                               "gender4", 
                               "faminc_new",
                               "educ", 
                               "race", 
                               "employ", 
                               "trump"),
                         na.rm=T)
marginaleffects1.df <- as.data.frame(relig.inter$est.bin)
marginaleffects1.df$z <- (relig.inter$est.bin$`1`[,2])/(relig.inter$est.bin$`1`[,3])
marginaleffects1.df$p <- z2p(marginaleffects1.df$z)

# For Muslims
relig.inter <- interflex("binning", 
                         data = cces,
                         Y="CC22_331c",
                         D="muslim",
                         X="religiosity",
                         Z = c("democrat", 
                               "region", 
                               "gender4", 
                               "faminc_new",
                               "educ",
                               "race", 
                               "employ", 
                               "trump"),
                         na.rm=T)
marginaleffects2.df <- as.data.frame(relig.inter$est.bin)
marginaleffects2.df$z <- (relig.inter$est.bin$`1`[,2])/(relig.inter$est.bin$`1`[,3])
marginaleffects2.df$p <- z2p(marginaleffects2.df$z)

# For Jews
relig.inter <- interflex("binning", 
                         data = cces,
                         Y="CC22_331c",
                         D="jew",
                         X="religiosity",
                         Z = c("democrat",
                               "region", 
                               "gender4", 
                               "faminc_new", 
                               "educ", 
                               "race", 
                               "employ", 
                               "trump"),
                         na.rm=T)
marginaleffects3.df <- as.data.frame(relig.inter$est.bin)
marginaleffects3.df$z <- (relig.inter$est.bin$`1`[,2])/(relig.inter$est.bin$`1`[,3])
marginaleffects3.df$p <- z2p(marginaleffects3.df$z)

# For Catholics
relig.inter <- interflex("binning", 
                         data = cces,
                         Y="CC22_331c",
                         D="catholic",
                         X="religiosity",
                         Z = c("democrat", 
                               "region",
                               "gender4", 
                               "faminc_new", 
                               "educ", 
                               "race", 
                               "employ", 
                               "trump"),
                         na.rm=T)
marginaleffects4.df <- as.data.frame(relig.inter$est.bin)
marginaleffects4.df$z <- (relig.inter$est.bin$`1`[,2])/(relig.inter$est.bin$`1`[,3])
marginaleffects4.df$p <- z2p(marginaleffects4.df$z)

# Combining all four dataframes together
alltogether.df  <- as.data.frame(rbind(
  marginaleffects1.df,
  marginaleffects2.df,
  marginaleffects3.df,
  marginaleffects4.df))

# Renaming the column names
colnames(alltogether.df) <- c("X",
                              "coef",
                              "sd",
                              "CI.lower",
                              "CI.upper",
                              "z",
                              "p")

# Adding a variable for 'treatment' (religion)
alltogether.df$Treatment <- as.factor(c("Mormon", "Mormon", "Mormon",
                                        "Muslim", "Muslim", "Muslim",
                                        "Jew", "Jew", "Jew",
                                        "Catholic", "Catholic", "Catholic"))

# Adding a variable for the attitudes
alltogether.df$Attitudes <- as.factor(rep(c("Least Religious", 
                                            "Average", 
                                            "Highly Religious"),
                                          4))

# Removing those whose attitudes were simply average
alltogether.df <- subset(alltogether.df,
                         Attitudes != "Average")

# Adding a variable that indicates the p-value
alltogether.df <- alltogether.df %>%
  mutate(star = case_when(p <=.1 & p > .05 ~ "+",
                          p <= .05 & p >.01 ~ "*",
                          p <= .01 & p >.001 ~ "**", 
                          p <= .001 ~ "***"))

# Making a plot!
dv2  <- ggplot(data = alltogether.df, 
               aes(Attitudes, 
                   coef, 
                   color = Treatment, 
                   shape = Treatment)) + 
  geom_point(stat="identity", 
             position = position_dodge(width = .3, 
                                       preserve = "total")) + 
  geom_linerange(data = alltogether.df, 
                 aes(ymin = CI.lower,
                     ymax=CI.upper),
                 position = position_dodge(width = .3, 
                                           preserve = "total")) + 
  coord_flip() + 
  theme(axis.title=element_text(size=8)) + 
  theme(axis.text=element_text(size=8)) + 
  theme(legend.text=element_text(size=7)) + 
  theme(legend.title=element_text(size=7)) +
  geom_hline(yintercept = 0, 
             lty=2) +
  theme_bw() +
  theme(legend.position = "bottom", 
        panel.grid.minor.x = element_blank()) +
  scale_color_manual(values = c("#a11111",
                                "darkblue", 
                                "#c9a808", 
                                "#019001")) +
  labs(y="ITT: Marginal Effects on Immigration",
       x = "", 
       title = "", 
       caption = "Bars indicate 95% confidence interval. Stars indicate statistical significance.") +
  geom_text(data = alltogether.df, 
            aes(label = star), 
            position = position_dodge(width = .3),
            vjust = -.001, 
            show.legend = FALSE) + 
  theme(text = element_text(family = "serif"), 
        plot.caption = element_text(hjust = 0))

dv2

# Saving out the plot
ggsave(str_c(plot_path, "Marginal Effects Immigration Interaction.png"),
       plot = dv2,
       width = 6,
       height = 4,
       dpi = 300,
       bg = "white")

# Abortion Regression
abortioninteract <- lm(CC22_332a ~ mormon + muslim + jew + catholic + mormon*religiosity + muslim*religiosity + jew*religiosity + catholic*religiosity + democrat + as.factor(region) + as.factor(gender4) + faminc_new + educ + as.factor(race) + employ + religiosity + trump, 
                       data = cces)
summary(abortioninteract)

# Finding the marginal effects for Mormons
relig.inter <- interflex("binning", 
                         data = cces,
                         Y="CC22_332a",
                         D="mormon",
                         X="religiosity",
                         Z = c("democrat", 
                               "region", 
                               "gender4",
                               "faminc_new", 
                               "educ", 
                               "race", 
                               "employ", 
                               "trump"),
                         na.rm=T)
marginaleffects1.df <- as.data.frame(relig.inter$est.bin)
marginaleffects1.df$z <- (relig.inter$est.bin$`1`[,2])/(relig.inter$est.bin$`1`[,3])
marginaleffects1.df$p <- z2p(marginaleffects1.df$z)

# For Muslims
relig.inter <- interflex("binning", 
                         data = cces,
                         Y="CC22_332a",
                         D="muslim",
                         X="religiosity",
                         Z = c("democrat", 
                               "region",
                               "gender4", 
                               "faminc_new",
                               "educ", 
                               "race", 
                               "employ", 
                               "trump"),
                         na.rm=T)
marginaleffects2.df <- as.data.frame(relig.inter$est.bin)
marginaleffects2.df$z <- (relig.inter$est.bin$`1`[,2])/(relig.inter$est.bin$`1`[,3])
marginaleffects2.df$p <- z2p(marginaleffects2.df$z)

# For Jews
relig.inter <- interflex("binning", 
                         data = cces,
                         Y="CC22_332a",
                         D="jew",
                         X="religiosity",
                         Z = c("democrat", 
                               "region",
                               "gender4",
                               "faminc_new", 
                               "educ",
                               "race",
                               "employ",
                               "trump"),
                         na.rm=T)
marginaleffects3.df <- as.data.frame(relig.inter$est.bin)
marginaleffects3.df$z <- (relig.inter$est.bin$`1`[,2])/(relig.inter$est.bin$`1`[,3])
marginaleffects3.df$p <- z2p(marginaleffects3.df$z)

# For Catholics
relig.inter <- interflex("binning", 
                         data = cces,
                         Y="CC22_332a",
                         D="catholic",
                         X="religiosity",
                         Z = c("democrat", 
                               "region", 
                               "gender4", 
                               "faminc_new", 
                               "educ",
                               "race", 
                               "employ", 
                               "trump"),
                         na.rm=T)
marginaleffects4.df <- as.data.frame(relig.inter$est.bin)
marginaleffects4.df$z <- (relig.inter$est.bin$`1`[,2])/(relig.inter$est.bin$`1`[,3])
marginaleffects4.df$p <- z2p(marginaleffects4.df$z)

# Combining all the marginal effects into a dataframe
alltogether.df  <- as.data.frame(rbind(
  marginaleffects1.df,
  marginaleffects2.df,
  marginaleffects3.df,
  marginaleffects4.df
))

# Renaming the columns
colnames(alltogether.df) <- c("X",
                              "coef",
                              "sd",
                              "CI.lower",
                              "CI.upper",
                              "z",
                              "p")

# Adding a treatment variable, giving the treatment variable values
alltogether.df$Treatment <- as.factor(c("Mormon", "Mormon", "Mormon",
                                        "Muslim", "Muslim", "Muslim",
                                        "Jew", "Jew", "Jew",
                                        "Catholic", "Catholic", "Catholic"))

# Adding an attitude variable, giving it values
alltogether.df$Attitudes <- as.factor(rep(c("Least Religious", 
                                            "Average",
                                            "Highly Religious"),
                                          4))

# Removing those who had an average level of religiosity
alltogether.df <- subset(alltogether.df, Attitudes != "Average")

# Adding a variable that visually indicates p-value
alltogether.df <- alltogether.df %>%
  mutate(star = case_when(p <=.1 & p > .05 ~ "+",
                          p <= .05 & p >.01 ~ "*",
                          p <= .01 & p >.001 ~ "**", 
                          p <= .001 ~ "***"))

# Making a plot
dv3  <- ggplot(data = alltogether.df , 
               aes(Attitudes, 
                   coef, 
                   color = Treatment, 
                   shape = Treatment)) + 
  geom_point(stat = "identity", 
             position = position_dodge(width = .3, 
                                       preserve = "total")) + 
  geom_linerange(data = alltogether.df, 
                 aes(ymin = CI.lower,
                     ymax = CI.upper), 
                 position = position_dodge(width = .3, 
                                           preserve = "total")) + 
  coord_flip() + 
  theme(axis.title=element_text(size=8)) + 
  theme(axis.text=element_text(size=8)) + 
  theme(legend.text=element_text(size=7)) + 
  theme(legend.title=element_text(size=7)) +
  geom_hline(yintercept = 0, 
             lty=2) +
  theme_bw() +
  theme(legend.position = "bottom",
        panel.grid.minor.x = element_blank()) +
  scale_color_manual(values = c("#a11111",
                                "darkblue", 
                                "#c9a808", 
                                "#019001")) +
  labs(y="ITT: Marginal Effects on Abortion", 
       x = "",
       title = "", 
       caption = "Bars indicate 95% confidence interval. Stars indicate statistical significance.") +
  geom_text(data = alltogether.df, 
            aes(label = star), 
            position = position_dodge(width = .3),
            vjust = -.001, 
            show.legend = FALSE) + 
  theme(text = element_text(family = "serif"), 
        plot.caption = element_text(hjust = 0))

dv3

ggsave(str_c(plot_path, "Marginal Effects Abortion Interactions.png"),
       plot = dv3,
       width = 6,
       height = 4,
       dpi = 300,
       bg = "white")

# Trust in the Federal Government Regression
trustinteract <- lm(CC22_423 ~ mormon + muslim + jew + catholic + mormon*religiosity + muslim*religiosity + jew*religiosity + catholic*religiosity + democrat + as.factor(region) + as.factor(gender4) + faminc_new + educ + as.factor(race) + employ + religiosity + trump,
                    data = cces)
summary(trustinteract)

# Marginal Effects for Mormons
relig.inter <- interflex("binning", 
                         data = cces,
                         Y="CC22_423",
                         D="mormon",
                         X="religiosity",
                         Z = c("democrat", 
                               "region", 
                               "gender4", 
                               "faminc_new", 
                               "educ",
                               "race", 
                               "employ", 
                               "trump"),
                         na.rm=T)
marginaleffects1.df <- as.data.frame(relig.inter$est.bin)
marginaleffects1.df$z <- (relig.inter$est.bin$`1`[,2])/(relig.inter$est.bin$`1`[,3])
marginaleffects1.df$p <- z2p(marginaleffects1.df$z)

# For Muslims
relig.inter <- interflex("binning", 
                         data = cces,
                         Y="CC22_423",
                         D="muslim",
                         X="religiosity",
                         Z = c("democrat", 
                               "region", 
                               "gender4", 
                               "faminc_new", 
                               "educ",
                               "race", 
                               "employ",
                               "trump"),
                         na.rm=T)
marginaleffects2.df <- as.data.frame(relig.inter$est.bin)
marginaleffects2.df$z <- (relig.inter$est.bin$`1`[,2])/(relig.inter$est.bin$`1`[,3])
marginaleffects2.df$p <- z2p(marginaleffects2.df$z)

# For Jews
relig.inter <- interflex("binning", 
                         data = cces,
                         Y="CC22_423",
                         D="jew",
                         X="religiosity",
                         Z = c("democrat",
                               "region", 
                               "gender4",
                               "faminc_new", 
                               "educ", 
                               "race", 
                               "employ",
                               "trump"),
                         na.rm=T)
marginaleffects3.df <- as.data.frame(relig.inter$est.bin)
marginaleffects3.df$z <- (relig.inter$est.bin$`1`[,2])/(relig.inter$est.bin$`1`[,3])
marginaleffects3.df$p <- z2p(marginaleffects3.df$z)

# For Catholics
relig.inter <- interflex("binning", 
                         data = cces,
                         Y="CC22_423",
                         D="catholic",
                         X="religiosity",
                         Z = c("democrat",
                               "region", 
                               "gender4",
                               "faminc_new", 
                               "educ", 
                               "race", 
                               "employ", 
                               "trump"),
                         na.rm=T)
marginaleffects4.df <- as.data.frame(relig.inter$est.bin)
marginaleffects4.df$z <- (relig.inter$est.bin$`1`[,2])/(relig.inter$est.bin$`1`[,3])
marginaleffects4.df$p <- z2p(marginaleffects4.df$z)

# Combining all four marginal effect dataframes
alltogether.df  <- as.data.frame(rbind(
  marginaleffects1.df,
  marginaleffects2.df,
  marginaleffects3.df,
  marginaleffects4.df
))

# Renaming the columns
colnames(alltogether.df) <- c("X",
                              "coef",
                              "sd",
                              "CI.lower",
                              "CI.upper",
                              "z",
                              "p")

# Adding a treatment variable, giving it values
alltogether.df$Treatment <- as.factor(c("Mormon", "Mormon", "Mormon",
                                        "Muslim", "Muslim", "Muslim",
                                        "Jew", "Jew", "Jew",
                                        "Catholic", "Catholic", "Catholic"
))

# Adding an attitudes variable, giving it values
alltogether.df$Attitudes <- as.factor(rep(c("Least Religious", 
                                            "Average", 
                                            "Highly Religious"),
                                          4))

# Removing those with average religiosity from this dataset
alltogether.df <- subset(alltogether.df, 
                         Attitudes != "Average")

# Adding a variable that gives a visual cue to what the p-values are
alltogether.df <- alltogether.df %>%
  mutate(star = case_when(p <=.1 & p > .05 ~ "+",
                          p <= .05 & p >.01 ~ "*",
                          p <= .01 & p >.001 ~ "**", 
                          p <= .001 ~ "***"))

# Making a plot
dv4  <- ggplot(data=alltogether.df, 
               aes(Attitudes,
                   coef, 
                   color = Treatment, 
                   shape = Treatment)) + 
  geom_point(stat="identity", 
             position = position_dodge(width = .3, 
                                       preserve = "total")) + 
  geom_linerange(data = alltogether.df, 
                 aes(ymin = CI.lower,
                     ymax = CI.upper), 
                 position = position_dodge(width = .3,
                                           preserve = "total")) + 
  coord_flip() + 
  theme(axis.title=element_text(size=8)) + 
  theme(axis.text=element_text(size=8)) + 
  theme(legend.text=element_text(size=7)) + 
  theme(legend.title=element_text(size=7)) +
  geom_hline(yintercept = 0, lty=2) +
  theme_bw() +
  theme(legend.position = "bottom", 
        panel.grid.minor.x = element_blank()) +
  scale_color_manual(values = c("#a11111",
                                "darkblue",
                                "#c9a808", 
                                "#019001")) +
  labs(y="ITT: Marginal Effects on Trust in the Federal Government",
       x = "", 
       title = "", 
       caption = "Bars indicate 95% confidence interval. Stars indicate statistical significance.") +
  geom_text(data = alltogether.df, 
            aes(label = star), 
            position = position_dodge(width = .3),
            vjust = -.001, 
            show.legend = FALSE) + 
  theme(text = element_text(family = "serif"), 
        plot.caption = element_text(hjust = 0))

dv4

# Saving out the plot
ggsave(str_c(plot_path, "Marginal Effects Trust in the Fed Govt Interactions.png"),
       plot = dv4,
       width = 6,
       height = 4,
       dpi = 300,
       bg = "white")

# Creating a table that has the interaction regressions in it
stargazer(trustinteract, 
          covariate.labels = c("Intercept", 
                               "Mormons", 
                               "Muslims", 
                               "Jews", 
                               "Catholics", 
                               "Religiosity", 
                               "Democrats", 
                               "Midwest", 
                               "South", 
                               "West", 
                               "Woman", 
                               "Other Gender", 
                               "Income",
                               "Education",
                               "Black", 
                               "Hispanic", 
                               "Asian", 
                               "Native American", 
                               "Middle Eastern", 
                               "Two or More Races", 
                               "Other", 
                               "Employment", 
                               "Trump",
                               "Mormon*Religiosity", 
                               "Muslim*Religiosity",
                               "Jew*Religiosity", 
                               "Catholic*Religiosity"), 
          type = "html", 
          style = "apsr", 
          title = "Religion and Religiousity Interaction Regression Results", 
          dep.var.labels=c("Trust in the Federal Government"), 
          notes = c("Base categories: Northeast, Male, White"), 
          digits=3, 
          intercept.bottom = FALSE, 
          intercept.top = TRUE, 
          out = str_c(table_path,
                      "interaction_reg.htm"))

```

What happens with other religions?
```{r}
# Looking at other religions, specifically Protestants and Buddhists:
cces$protestant <- ifelse(cces$religpew == 1, 1, 0)
table(cces$protestant)

cces$buddhist <- ifelse(cces$religpew == 7, 1, 0)
table(cces$buddhist)

# Healthcare Regression
healthcaremanyreligs <- lm(CC22_327a ~ mormon + muslim + jew + catholic + protestant + buddhist + democrat + as.factor(region) + as.factor(gender4) + faminc_new + educ + as.factor(race) + employ + religiosity + trump, 
                           data = cces)
summary(healthcaremanyreligs)

healthcare2 <- tidy(healthcaremanyreligs, 
                    conf.int = TRUE)

healthcare2$try <- ifelse(healthcare2$term %in% c("muslim", 
                                                  "mormon", 
                                                  "catholic", 
                                                  "democrat",
                                                  "protestant",
                                                  "buddhist",
                                                  "religiosity"), 
                          1, 0)

# Making a health care marginal effects plot
health_grph <- ggplot(healthcare2 %>% filter(!(term %in% c("(Intercept)",
                                                      "as.factor(gender4)2",
                                                      "as.factor(gender4)3",
                                                      "as.factor(gender4)4",
                                                      "as.factor(race)2",
                                                      "as.factor(race)3",
                                                      "as.factor(race)4",
                                                      "as.factor(race)5",
                                                      "as.factor(race)6",
                                                      "as.factor(race)7",
                                                      "as.factor(race)8", 
                                                      "as.factor(region)2",
                                                      "as.factor(region)3",
                                                      "as.factor(region)4", 
                                                      "trump", 
                                                      "faminc_new",
                                                      "employ", 
                                                      "educ"))),
                 mapping = aes(x = term, 
                               y = estimate, 
                               ymin = conf.low, 
                               ymax = conf.high, 
                               color = try)) +
  geom_pointrange() +
  coord_flip() +
  labs(title = "", 
       y = "Marginal Effects on Healthcare", 
       x = "", 
       caption = "Effect of Ethno-Religious Groups on Healthcare Opinions \nDots represent the marginal effects. The bars are 95% confidence intervals. The black color indicates statistical significance.") +
  theme_minimal() +
  geom_hline(yintercept = 0, 
             color = "gray30", 
             linetype = "dashed") +
  scale_x_discrete(limits = c("religiosity", 
                              "democrat",
                              "protestant", 
                              "muslim",
                              "mormon", 
                              "jew", 
                              "catholic", 
                              "buddhist"), 
                   labels = c("Religiousity", 
                              "Democrat", 
                              "Protestants", 
                              "Muslims", 
                              "Mormons", 
                              "Jews", 
                              "Catholics", 
                              "Buddhists")) + 
  scale_color_gradient(low = "grey70", 
                       high = "black") +
  theme(legend.position = "none",
        plot.caption = element_text(hjust = 0))

health_grph

# Saving out the graph
ggsave(str_c(plot_path, "Marginal Effects on Healthcare, Many Religs.png"),
       plot = health_grph,
       width = 6,
       height = 4,
       dpi = 300,
       bg = "white")

# Immigration Regression
immigrationmanyreligs <- lm(CC22_331c ~ mormon + muslim + jew + catholic + protestant + buddhist + democrat + as.factor(region) + as.factor(gender4) + faminc_new + educ + as.factor(race) + employ + religiosity + trump, 
                            data = cces)

summary(immigrationmanyreligs)

immigration2 <- tidy(immigrationmanyreligs, 
                     conf.int = TRUE)

immigration2$try <- ifelse(immigration2$term %in% c("muslim",
                                                  "catholic", 
                                                  "democrat", 
                                                  "protestant",
                                                  "religiosity"), 
                          1, 0)

# Making a marginal effects plot
immigration_grph <- ggplot(immigration2 %>% filter(!(term %in% c("(Intercept)",
                                            "as.factor(gender4)2",
                                            "as.factor(gender4)3",
                                            "as.factor(gender4)4",
                                            "as.factor(race)2",
                                            "as.factor(race)3",
                                            "as.factor(race)4",
                                            "as.factor(race)5",
                                            "as.factor(race)6",
                                            "as.factor(race)7",
                                            "as.factor(race)8",
                                            "as.factor(region)2",
                                            "as.factor(region)3",
                                            "as.factor(region)4",
                                            "trump",
                                            "faminc_new",
                                            "employ",
                                            "educ"))),
       mapping = aes(x = term,
                     y = estimate, 
                     ymin = conf.low, 
                     ymax = conf.high, 
                     color = try)) +
  geom_pointrange() +
  coord_flip() +
  labs(title = "Effect of Ethno-Religious Groups on Immigration Opinions", 
       y = "",
       x = "Estimate", 
       caption = "Black color indicates statistical significance") +
  theme_minimal() +
  geom_hline(yintercept = 0,
             color = "gray30",
             linetype = "dashed") +
  scale_x_discrete(limits = c("religiosity",
                              "democrat",
                              "protestant",
                              "muslim",
                              "mormon",
                              "jew",
                              "catholic",
                              "buddhist"), 
                   labels = c("Religiousity", "
                              Democrat",
                              "Protestants", 
                              "Muslims",
                              "Mormons",
                              "Jews", 
                              "Catholics",
                              "Buddhists")) + 
  scale_color_gradient(low = "grey70", 
                       high = "black") +
  theme(legend.position = "none", 
        plot.caption = element_text(hjust = 0))

immigration_grph

ggsave(str_c(plot_path, "Marginal Effects on Immigration Opinions, Many Religs.png"),
       plot = immigration_grph,
       width = 6,
       height = 4,
       dpi = 300,
       bg = "white")

# Abortion Regression
abortionmanyreligs <- lm(CC22_332a ~ mormon + muslim + jew + catholic + protestant + buddhist + democrat + as.factor(region) + as.factor(gender4) + faminc_new + educ + as.factor(race) + employ + religiosity + trump, 
                         data = cces)

summary(abortionmanyreligs)

abort2 <- tidy(abortionmanyreligs, 
                    conf.int = TRUE)

abort2$try <- ifelse(abort2$term %in% c("muslim", 
                                                  "catholic",
                                                  "democrat", 
                                                  "protestant",
                                                  "buddhist",
                                                  "religiosity"),
                          1, 0)

# Making a marginal effects plot
abortion_grph <- ggplot(abort2 %>% filter(!(term %in% c("(Intercept)",
                                            "as.factor(gender4)2",
                                            "as.factor(gender4)3",
                                            "as.factor(gender4)4",
                                            "as.factor(race)2",
                                            "as.factor(race)3",
                                            "as.factor(race)4",
                                            "as.factor(race)5",
                                            "as.factor(race)6",
                                            "as.factor(race)7",
                                            "as.factor(race)8",
                                            "as.factor(region)2",
                                            "as.factor(region)3",
                                            "as.factor(region)4", 
                                            "trump",
                                            "faminc_new",
                                            "employ",
                                            "educ"))),
       mapping = aes(x = term, 
                     y = estimate,
                     ymin = conf.low, 
                     ymax = conf.high, 
                     color = try)) +
  geom_pointrange() +
  coord_flip() +
  labs(title = "Effect of Ethno-Religious Groups on Abortion Opinions", 
       y = "",
       x = "Estimate", 
       caption = "Black color indicates statistical significance") +
  theme_minimal() +
  geom_hline(yintercept = 0, 
             color = "gray30", 
             linetype = "dashed") +
  scale_x_discrete(limits = c("religiosity", 
                              "democrat",
                              "protestant",
                              "muslim", 
                              "mormon", 
                              "jew", 
                              "catholic", 
                              "buddhist"), 
                   labels = c("Religiousity", 
                              "Democrat", 
                              "Protestants",
                              "Muslims", 
                              "Mormons", 
                              "Jews", 
                              "Catholics", 
                              "Buddhists")) + 
  scale_color_gradient(low = "grey70",
                       high = "black") +
  theme(legend.position = "none", 
        plot.caption = element_text(hjust = 0))

abortion_grph

# Saving out the plot
ggsave(str_c(plot_path, "Marginal Effects on Abortion Opinions, Many Religs.png"),
       plot = abortion_grph,
       width = 6,
       height = 4,
       dpi = 300,
       bg = "white")

# Trust in the federal government 
trustmanyreligs <- lm(CC22_423 ~ mormon + muslim + jew + catholic + protestant + buddhist + democrat + as.factor(region) + as.factor(gender4) + faminc_new + educ + as.factor(race) + employ + religiosity + trump, 
                      data = cces)

summary(trustmanyreligs)

trust2 <- tidy(trustmanyreligs, 
                    conf.int = TRUE)

trust2$try <- ifelse(trust2$term %in% c("muslim",
                                                  "catholic", 
                                                  "democrat", 
                                                  "protestant",
                                                  "buddhist",
                                                  "religiosity"),
                          1, 0)

# Making a marginal effects plot
trust_grph <- ggplot(trust2 %>% filter(!(term %in% c("(Intercept)",
                                            "as.factor(gender4)2",
                                            "as.factor(gender4)3",
                                            "as.factor(gender4)4",
                                            "as.factor(race)2",
                                            "as.factor(race)3",
                                            "as.factor(race)4",
                                            "as.factor(race)5",
                                            "as.factor(race)6",
                                            "as.factor(race)7",
                                            "as.factor(race)8",
                                            "as.factor(region)2",
                                            "as.factor(region)3",
                                            "as.factor(region)4", 
                                            "trump", 
                                            "faminc_new", 
                                            "employ",
                                            "educ"))),
       mapping = aes(x = term, 
                     y = estimate,
                     ymin = conf.low, 
                     ymax = conf.high,
                     color = try)) +
  geom_pointrange() +
  coord_flip() +
  labs(title = "Figure 14: Effect of Ethno-Religious Groups on Trust in the Federal Government",
       y = "", 
       x = "Estimate", 
       caption = "Black color indicates statistical significance") +
  theme_minimal() +
  geom_hline(yintercept = 0, 
             color = "gray30",
             linetype = "dashed") +
  scale_x_discrete(limits = c("religiosity", 
                              "democrat",
                              "protestant",
                              "muslim",
                              "mormon", 
                              "jew", 
                              "catholic", 
                              "buddhist"), 
                   labels = c("Religiousity", 
                              "Democrat", 
                              "Protestants",
                              "Muslims",
                              "Mormons", 
                              "Jews", 
                              "Catholics", 
                              "Buddhists")) +
  scale_color_gradient(low = "grey70", 
                       high = "black") +
  theme(legend.position = "none", 
        plot.caption = element_text(hjust = 0))

trust_grph

# Saving out the plot
ggsave(str_c(plot_path, "Marginal Effects on Trust in the Fed Govt, Many Religs.png"),
       plot = trust_grph,
       width = 6,
       height = 4,
       dpi = 300,
       bg = "white")

# Also saving out this one as a graph
stargazer(trustmanyreligs, 
          covariate.labels = c("Intercept",
                               "Mormons", 
                               "Muslims", 
                               "Jews", 
                               "Catholics",
                               "Protestants", 
                               "Buddhists", 
                               "Democrats", 
                               "Midwest", 
                               "South", 
                               "West", 
                               "Woman", 
                               "Other Gender", 
                               "Income", 
                               "Education",
                               "Black", 
                               "Hispanic", 
                               "Asian", 
                               "Native American", 
                               "Middle Eastern", 
                               "Two or More Races", 
                               "Other Race",
                               "Employment", 
                               "Religiosity", 
                               "Christian Nationalism"), 
          type = "html", 
          style = "apsr",
          title = "Figure 8: Many Religions' Regression Results",
          dep.var.labels=c("Healthcare", 
                           "Immigration",
                           "Abortion"), 
          notes = c("Base categories: Northeast, Male, White"), 
          out = str_c(table_path,
                      "trustmanyreligs.htm"))
```

Making Basic Graphs
```{r}
# Healthcare
healthcare2 <- tidy(healthcare, 
                    conf.int = TRUE)

healthcare2$try <- ifelse(healthcare2$term %in% c("muslim",
                                                  "catholic",
                                                  "democrat",
                                                  "religiosity"), 
                          1, 0)

healthcare_grph2 <- ggplot(healthcare2 %>% filter(!(term %in% c("(Intercept)",
                                            "as.factor(gender4)2",
                                            "as.factor(gender4)3",
                                            "as.factor(gender4)4",
                                            "as.factor(race)2",
                                            "as.factor(race)3",
                                            "as.factor(race)4",
                                            "as.factor(race)5",
                                            "as.factor(race)6",
                                            "as.factor(race)7",
                                            "as.factor(race)8",
                                            "as.factor(region)2",
                                            "as.factor(region)3",
                                            "as.factor(region)4",
                                            "trump",
                                            "faminc_new",
                                            "employ",
                                            "educ"))),
       mapping = aes(x = term, 
                     y = estimate,
                     ymin = conf.low, 
                     ymax = conf.high, 
                     color = try)) +
  geom_pointrange() +
  coord_flip() +
  labs(title = "", 
       y = "Marginal Effects on Healthcare", 
       x = "", 
       caption = "Effect of Ethno-Religious Groups on Healthcare Opinions \nDots represent the marginal effects. The bars are 95% confidence intervals. The black color indicates statistical significance.") +
  theme_minimal() +
  geom_hline(yintercept = 0, 
             color = "gray30",
             linetype = "dashed") +
  scale_x_discrete(limits = c("religiosity",
                              "democrat", 
                              "muslim", 
                              "mormon", 
                              "jew", 
                              "catholic"), 
                   labels = c("Religiousity", 
                              "Democrat",
                              "Muslims",
                              "Mormons", 
                              "Jews",
                              "Catholics")) + 
  scale_color_gradient(low = "grey70",
                       high = "black") +
  theme(legend.position = "none",
        plot.caption = element_text(hjust = 0))

healthcare_grph2

# Saving out the plot
ggsave(str_c(plot_path, "Marginal Effects on Healthcare.png"),
       plot = healthcare_grph2,
       width = 6,
       height = 4,
       dpi = 300,
       bg = "white")

# Immigration
immigration2 <- tidy(immigration, 
                     conf.int = TRUE)

immigration2$try <- ifelse(immigration2$term %in% c("mormon",
                                                    "muslim",
                                                    "catholic", 
                                                    "democrat",
                                                    "religiosity"), 
                           1, 0)

immigration_grph2 <- ggplot(immigration2 %>% filter(!(term %in% c("(Intercept)",
                                             "as.factor(gender4)2",
                                             "as.factor(gender4)3",
                                             "as.factor(gender4)4",
                                             "as.factor(race)2",
                                             "as.factor(race)3",
                                             "as.factor(race)4",
                                             "as.factor(race)5",
                                             "as.factor(race)6",
                                             "as.factor(race)7",
                                             "as.factor(race)8",
                                             "as.factor(region)2",
                                             "as.factor(region)3",
                                             "as.factor(region)4", 
                                             "trump",
                                             "faminc_new",
                                             "employ",
                                             "educ"))),
       mapping = aes(x = term,
                     y = estimate, 
                     ymin = conf.low, 
                     ymax = conf.high, 
                     color = try)) +
  geom_pointrange() +
  coord_flip() +
  labs(title = "", 
       y = "Marginal Effects on Immigration",
       x = "", 
       caption = "Effect of Ethno-Religious Groups on Immigration Opinions \nDots represent the marginal effects. The bars are 95% confidence intervals. The black color indicates statistical significance.") +
  theme_minimal() +
  geom_hline(yintercept = 0, 
             color = "gray30", 
             linetype = "dashed") +
  scale_x_discrete(limits = c("religiosity",
                              "democrat",
                              "muslim", 
                              "mormon", 
                              "jew", 
                              "catholic"), 
                   labels = c("Religiousity",
                              "Democrat", 
                              "Muslims",
                              "Mormons", 
                              "Jews", 
                              "Catholics")) + 
  scale_color_gradient(low = "grey70", 
                       high = "black") +
  theme(legend.position = "none", 
        plot.caption = element_text(hjust = 0))

immigration_grph2

# Saving out the plot
ggsave(str_c(plot_path, "Marginal Effects on Immigration.png"),
       plot = immigration_grph2,
       width = 6,
       height = 4,
       dpi = 300,
       bg = "white")

# Abortion
abortion2 <- tidy(abortion, 
                  conf.int = TRUE)

abortion2$try <- ifelse(abortion2$term %in% c("mormon", 
                                              "muslim",
                                              "jew", 
                                              "catholic", 
                                              "democrat",
                                              "religiosity"), 
                        1, 0)

# Making a marginal effects plot
abortion_grph2 <- ggplot(abortion2 %>% filter(!(term %in% c("(Intercept)",
                                          "as.factor(gender4)2",
                                          "as.factor(gender4)3",
                                          "as.factor(gender4)4",
                                          "as.factor(race)2",
                                          "as.factor(race)3",
                                          "as.factor(race)4",
                                          "as.factor(race)5",
                                          "as.factor(race)6",
                                          "as.factor(race)7",
                                          "as.factor(race)8",
                                          "as.factor(region)2",
                                          "as.factor(region)3",
                                          "as.factor(region)4", 
                                          "trump", 
                                          "faminc_new", 
                                          "employ", 
                                          "educ"))),
       mapping = aes(x = term,
                     y = estimate, 
                     ymin = conf.low, 
                     ymax = conf.high)) +
  geom_pointrange() +
  coord_flip() +
  labs(title = "", 
       y = "Marginal Effects on Abortion",
       x = "", 
       caption = "Effect of Ethno-Religious Groups on Abortion Opinions \nDots represent the marginal effects. The bars are 95% confidence intervals. The black color indicates statistical significance.") +
  theme_minimal() +
  geom_hline(yintercept = 0, 
             color = "gray30", 
             linetype = "dashed") +
  scale_x_discrete(limits = c("religiosity", 
                              "democrat", 
                              "muslim", 
                              "mormon", 
                              "jew", 
                              "catholic"), 
                   labels = c("Religiousity", 
                              "Democrat",
                              "Muslims",
                              "Mormons",
                              "Jews", 
                              "Catholics")) + 
  theme(legend.position = "none", 
        plot.caption = element_text(hjust = 0))

abortion_grph2

# Saving out the plot
ggsave(str_c(plot_path, "Marginal Effects on Abortion.png"),
       plot = abortion_grph2,
       width = 6,
       height = 4,
       dpi = 300,
       bg = "white")

# Trust in the Federal Government
trust2 <- tidy(trust, 
               conf.int = TRUE)

trust2$try <- ifelse(trust2$term %in% c("muslim",
                                        "jew",
                                        "catholic",
                                        "democrat", 
                                        "religiosity"),
                     1, 0)

# Making a marginal effects plot
trust_grph2 <- ggplot(trust2 %>% filter(!(term %in% c("(Intercept)", 
                                       "as.factor(gender4)2",
                                       "as.factor(gender4)3",
                                       "as.factor(gender4)4",
                                       "as.factor(race)2",
                                       "as.factor(race)3",
                                       "as.factor(race)4",
                                       "as.factor(race)5",
                                       "as.factor(race)6",
                                       "as.factor(race)7",
                                       "as.factor(race)8",
                                       "as.factor(region)2",
                                       "as.factor(region)3",
                                       "as.factor(region)4", 
                                       "trump", 
                                       "faminc_new", 
                                       "employ", 
                                       "educ"))),
       mapping = aes(x = term, 
                     y = estimate, 
                     ymin = conf.low, 
                     ymax = conf.high,
                     color = try)) +
  geom_pointrange() +
  coord_flip() +
  labs(title = "", 
       y = "Marginal Effects on Trust in the Federal Government",
       x = "", 
       caption = "Effect of Ethno-Religious Groups on Trust in the Federal Government \nDots represent the marginal effects. The bars are 95% confidence intervals. The black color indicates statistical significance.") +
  theme_minimal() +
  geom_hline(yintercept = 0, 
             color = "gray30", 
             linetype = "dashed") +
  scale_x_discrete(limits = c("religiosity", 
                              "democrat", 
                              "muslim",
                              "mormon",
                              "jew",
                              "catholic"), 
                   labels = c("Religiousity", 
                              "Democrat",
                              "Muslims", 
                              "Mormons", 
                              "Jews", 
                              "Catholics")) + 
  scale_color_gradient(low = "grey70",
                       high = "black") +
  theme(legend.position = "none", 
        plot.caption = element_text(hjust = 0))

trust_grph2

# Saving out the plot
ggsave(str_c(plot_path, "Marginal Effects on Trust in the Federal Government.png"),
       plot = trust_grph2,
       width = 6,
       height = 4,
       dpi = 300,
       bg = "white")
```

Taking religiosity out of the regressions
```{r}
# Economy without religiosity
economy <- lm(CC22_302 ~ mormon + muslim + jew + catholic + democrat + as.factor(region) + as.factor(gender4) + faminc_new + as.factor(educ) + as.factor(race) + employ + commonweight, 
              data = cces)

summary(economy)

# original economy
economy <- lm(CC22_302 ~ mormon + muslim + jew + catholic + democrat + as.factor(region) + as.factor(gender4) + faminc_new + as.factor(educ) + as.factor(race) + employ + religiosity + commonweight, 
              data = cces)

summary(economy)
# No real change

# Healthcare without religiosity
healthcare <- lm(CC22_302 ~ mormon + muslim + jew + catholic + democrat + as.factor(region) + as.factor(gender4) + faminc_new + as.factor(educ) + as.factor(race) + employ + commonweight, 
                 data = cces)

summary(healthcare)

# original healthcare
healthcare <- lm(CC22_302 ~ mormon + muslim + jew + catholic + democrat + as.factor(region) + as.factor(gender4) + faminc_new + as.factor(educ) + as.factor(race) + employ + religiosity + commonweight, 
                 data = cces)

summary(healthcare)
# No real change

# Immigration without religiosity
immigration <- lm(CC22_331c ~ mormon + muslim + jew + catholic + democrat + as.factor(region) + as.factor(gender4) + faminc_new + as.factor(educ) + as.factor(race) + employ + commonweight, 
                  data = cces)

summary(immigration)

#original immigration
immigration <- lm(CC22_331c ~ mormon + muslim + jew + catholic + democrat + as.factor(region) + as.factor(gender4) + faminc_new + as.factor(educ) + as.factor(race) + employ + religiosity,
                  data = cces)

summary(immigration)
# Some change

# Abortion without religiosity
abortion <- lm(CC22_332a ~ mormon + muslim + jew + catholic + democrat + as.factor(region) + as.factor(gender4) + faminc_new + as.factor(educ) + as.factor(race) + employ, 
               data = cces)

summary(abortion)

# original abortion
abortion <- lm(CC22_332a ~ mormon + muslim + jew + catholic + democrat + as.factor(region) + as.factor(gender4) + faminc_new + as.factor(educ) + as.factor(race) + employ + religiosity, 
               data = cces)

summary(abortion)
# This one also changes
```